# Generated by Django 4.1.4 on 2022-12-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_library", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="book_cover",
            field=models.ImageField(blank=True, upload_to="photos/%Y/%m/%d"),
        ),
        migrations.AlterField(
            model_name="status",
            name="status",
            field=models.CharField(
                choices=[
                    ("o", "On loan"),
                    ("a", "Available"),
                    ("r", "Reserved"),
                    ("c", "Currently_reading"),
                    ("n", "Next_in_line"),
                    ("d", "Done_reading"),
                ],
                default="a",
                help_text="Book availability",
                max_length=1,
            ),
        ),
    ]
