# Generated by Django 4.1.4 on 2022-12-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_library", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="num_pages",
            new_name="pg_num",
        ),
        migrations.AlterField(
            model_name="bookinstance",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("o", "On loan"),
                    ("a", "Available"),
                    ("r", "Reserved"),
                    ("c", "Currently_reading"),
                    ("n", "Next_in_line"),
                    ("d", "Done_reading"),
                ],
                default="a",
                help_text="Book availability",
                max_length=2,
            ),
        ),
    ]
