# Generated by Django 4.1.3 on 2022-12-25 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("my_library", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year_in_school",
                    models.CharField(
                        choices=[
                            ("FR", "Freshman"),
                            ("SO", "Sophomore"),
                            ("JR", "Junior"),
                            ("SR", "Senior"),
                            ("GR", "Graduate"),
                        ],
                        default="FR",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="status",
            name="status",
        ),
        migrations.AlterField(
            model_name="bookinstance",
            name="booktitle",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="my_library.book",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bookinstance",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="my_library.status",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="student",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="my_library.student",
                verbose_name="Student",
            ),
            preserve_default=False,
        ),
    ]
