# Generated by Django 4.1.3 on 2022-12-26 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("my_library", "0002_status_alter_book_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("En", "English"),
                            ("Pt", "Portuguese"),
                            ("Sp", "Spanish"),
                            ("He", "Hebrew"),
                            ("It", "Italian"),
                            ("Fr", "French"),
                        ],
                        help_text="Language",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="books",
                to="my_library.author",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="my_library.status",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="my_library.language",
            ),
        ),
    ]
