# Generated by Django 4.1.3 on 2022-12-25 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_library", "0002_student_remove_status_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="student",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
