# Generated by Django 4.1.3 on 2022-12-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_library", "0003_language_alter_book_author_alter_book_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="language",
            field=models.CharField(
                choices=[
                    ("English", "English"),
                    ("Portuguese", "Portuguese"),
                    ("Spanish", "Spanish"),
                    ("Hebrew", "Hebrew"),
                    ("Italian", "Italian"),
                    ("French", "French"),
                ],
                help_text="Language",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="status",
            field=models.CharField(
                choices=[
                    ("On_loan", "On_loan"),
                    ("Available", "Available"),
                    ("Reserved", "Reserved"),
                    ("Currently_reading", "Currently_reading"),
                    ("Next_in_line", "Next_in_line"),
                    ("Done_reading", "Done_reading"),
                ],
                help_text="Book availability",
                max_length=20,
            ),
        ),
    ]
