# Generated by Django 4.1.3 on 2022-12-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_library", "0003_remove_book_student_delete_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="status",
            name="status",
            field=models.CharField(
                choices=[
                    ("O", "On_loan"),
                    ("A", "Available"),
                    ("R", "Reserved"),
                    ("C", "Currently_reading"),
                    ("N", "Next_in_line"),
                    ("D", "Done_reading"),
                ],
                default="Available",
                help_text="Book availability",
                max_length=50,
            ),
        ),
    ]
