# Generated by Django 4.1.3 on 2022-12-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_library", "0004_alter_language_language_alter_status_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(default="Unkown", max_length=50),
        ),
        migrations.AlterField(
            model_name="book",
            name="book_cover",
            field=models.ImageField(upload_to="static/images/covers/"),
        ),
        migrations.DeleteModel(
            name="Author",
        ),
    ]
