# Generated by Django 4.1.3 on 2022-12-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_library", "0004_status_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={},
        ),
        migrations.AlterModelOptions(
            name="book",
            options={},
        ),
        migrations.AlterModelOptions(
            name="bookinstance",
            options={},
        ),
        migrations.AlterField(
            model_name="book",
            name="language",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="book",
            name="status",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="bookinstance",
            name="status",
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name="Language",
        ),
        migrations.DeleteModel(
            name="Status",
        ),
    ]
