# Generated by Django 4.1.3 on 2022-12-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_library", "0005_alter_book_author_alter_book_book_cover_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="book_cover",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/images/covers/"
            ),
        ),
    ]
