# Generated by Django 4.1.3 on 2022-12-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_library", "0007_alter_book_book_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="book_cover",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/photos/covers/"
            ),
        ),
    ]
