# Generated by Django 4.1.3 on 2023-01-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_library", "0009_alter_book_book_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="book_cover",
            field=models.ImageField(null=True, upload_to="static/images/covers/"),
        ),
        migrations.AlterField(
            model_name="book",
            name="summary",
            field=models.TextField(
                help_text="Enter a brief summary of the book", max_length=1000
            ),
        ),
    ]
