# Generated by Django 4.1.3 on 2023-01-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_library", "0010_alter_book_book_cover_alter_book_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="book_cover",
            field=models.ImageField(null=True, upload_to="media/"),
        ),
    ]
