# Generated by Django 4.1.3 on 2022-12-26 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("my_library", "0004_alter_language_language_alter_status_status"),
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookinstance",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="my_library.status"
            ),
        ),
    ]
